---
title: "R4journalists Notebook"
output: html_notebook
---

# A list of learning outcomes from R for Journalists

## [Chapter 2 outcomes](http://www.machlis.com/R4Journalists/wrap-up.html)

* Install packages with `install.packages()`

## [Chapter 3 outcomes](http://www.machlis.com/R4Journalists/wrap-up-1.html):

* Using `library()` to activate a package
* Using a function without loading the package by adding the function and two colons before the function name, e.g. `mypackage::myfunction()`
* Run R code from an external file with `source("locationofscript.R")`
* Combining columns with `cbind()` and rows with `rbind()`
* Showing (or changing) the names of an object with `names()`

## Chapter 4 outcomes:

* Importing data using the `rio` package. The `rio::import()` function detects file type, avoiding the need for format-specific packages or functions like `readxl`
* Using the `skip = ` parameter to skip unnecessary rows before the table headings
* Using the `col_names = F` parameter to indicate there are no headings
* Using the `which =` parameter to indicate the sheet you want to import (if a workbook)
* Using the `colClasses = c()` parameter to specify when you wish columns to be treated as a particular type of data (e.g. `c("character", "character")`) - especially useful for company numbers, phone numbers or other data which needs to be treated as a character (to prevent leading zeroes being removed)
* Using the `rep()` function to repeat a value a specified number of times, e.g `rep("character", 5)` or `colClasses = c(rep(“character”, 14), rep(“numeric”, 2))`
* Downloading data using `download.file()` (specify the URL, then the name you want to save it as)
* Scraping nicely formatted HTML tables using `rio::import("url goes here", format = "html", which = 1)`
* Scraping other HTML tables using the `htmltab` package
* Installing packages from GitHub using the `pacman` package (and alternatives)
* Converting data types using `readr` and functions such as `parse_number()`
* Cleaning column headings using `janitor` and the `clean_names()` function 
* Using `class()` to find out the type of object you have created (e.g. data frame)
* Using `str()` to see the type of object and the types of data within it (e.g. string, number, etc.)
* Data frames consist of vectors (columns) which have to be the same type. For that reason, if there are non-numbers in a column, the values will be **coerced** to text so that all values are the same type.
* Using `nrow()` and `ncol()` to fetch out the numbers of rows or columns (useful if looping)
* Accessing columns by $ and the column name
* Creating new columns by perfoming a calculation on the values in an existing column
* Creating data frames manually by creating each column as a vector with `c()` and combining them with `data.frame()`
* By default data frames convert character vectors into factor columns, so use `stringsAsFactors = FALSE` when creating the data frame to avoid this.
* "If one column is shorter than the other(s), R will sometimes repeat data from the shorter column - whether or not you want that to happen."
* Using the `tibble` package and `tibble()` function as an alternative to `data.frame()` - e.g. `theobject <- tibble::tibble(vector1, vector2, vector3)` this will throw an error if there are unequal columns and also doesn't default to factors. "it is a data frame, but with some special behaviors, such as how it prints. You’ll also notice that the candidates column is character strings, not factors."
* Exporting data using `rio::export()` specifying the name of the object, and a string for the filename to be created (including extension)
* Specifying an `.R` filetype will save a script that generates the object
* Saving objects using `save()` and the `.RData` file extension; loading those into the environment using `load()`
* Saving objects individually using `saveRDS()` and the `.rds` extension; loading those using `readRDS()`, making sure to assign to a named object
* Converting files from one format to another without having to import them, using `rio::convert()`
* Base R alternatives such as `read.csv()` and `read.table()`, and `write.csv()`; the `openxlsx` package for writing XLS files and `readr` for handling files; the [`googlesheets` package](https://github.com/jennybc/googlesheets) for reading from Google Sheets.
* Directions to the `rvest` package for scraping

## Chapter 5 outcomes



