---
title: "keyword_counting_mps"
output: html_document
---

# Counting keywords in MPs' gifts register

This is based on steps outlined in a [blog post by John Victor Anderson](http://johnvictoranderson.org/?p=115). 

First, we need to import the data, and export the column of keywords:

```{r}
#we add fileEncoding because the £ signs generate errors
#see https://stackoverflow.com/questions/14363085/invalid-multibyte-string-in-read-csv
gifts <- read.csv("gifts.csv", fileEncoding="latin1")
write.csv(gifts$donationdesc, 'keywordsastext.txt')
```

Now we re-import that data as a character object using `scan`:

```{r}
keywords <- scan('keywordsastext.txt', what="char", sep=",")
# We convert all text to lower case to prevent any case sensitive issues with counting
keywords <- tolower(keywords)
```

We now need to put this through a series of conversions before we can generate a table:

```{r}
#replace any punctuation
keywords <- gsub("[^[:alnum:][:space:]']", "", keywords)
#split on spaces
keywords.split <- strsplit(keywords, " ")
#turn to vector
keywordsvec <- unlist(keywords.split)
#turn to table
keywordstable <- table(keywordsvec)
```

That table is enough to create a CSV from:

```{r}
write.csv(keywordstable, 'keywordcount.csv')
```


